import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function App() {
    const [currentPage, setCurrentPage] = useState('home');
    return (_jsxs("div", { className: "flex h-screen bg-gray-900 text-gray-100", children: [_jsxs("div", { className: "w-48 bg-gray-800 border-r border-gray-700 p-6", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent", children: "PlugHub" }), _jsx("p", { className: "text-gray-400 text-xs mt-1", children: "VST3 Plugin Manager" })] }), _jsxs("nav", { className: "space-y-3", children: [_jsx("button", { onClick: () => setCurrentPage('home'), className: `w-full text-left px-4 py-2 rounded-lg transition ${currentPage === 'home'
                                    ? 'bg-blue-600 text-white'
                                    : 'text-gray-300 hover:bg-gray-700'}`, children: "\uD83D\uDD0D Browse GitHub" }), _jsx("button", { onClick: () => setCurrentPage('marketplace'), className: `w-full text-left px-4 py-2 rounded-lg transition ${currentPage === 'marketplace'
                                    ? 'bg-blue-600 text-white'
                                    : 'text-gray-300 hover:bg-gray-700'}`, children: "\uD83C\uDFA8 PlugHub Market" }), _jsx("button", { onClick: () => setCurrentPage('installed'), className: `w-full text-left px-4 py-2 rounded-lg transition ${currentPage === 'installed'
                                    ? 'bg-blue-600 text-white'
                                    : 'text-gray-300 hover:bg-gray-700'}`, children: "\u2713 Installed" }), _jsx("button", { onClick: () => setCurrentPage('settings'), className: `w-full text-left px-4 py-2 rounded-lg transition ${currentPage === 'settings'
                                    ? 'bg-blue-600 text-white'
                                    : 'text-gray-300 hover:bg-gray-700'}`, children: "\u2699\uFE0F Settings" })] }), _jsx("div", { className: "mt-8 pt-8 border-t border-gray-700", children: _jsx("p", { className: "text-xs text-gray-500", children: "v0.1.0" }) })] }), _jsxs("div", { className: "flex-1 overflow-hidden", children: [currentPage === 'home' && (_jsxs("div", { className: "flex flex-col h-full bg-gray-900", children: [_jsxs("div", { className: "p-8 border-b border-gray-700", children: [_jsx("h2", { className: "text-3xl font-bold text-white mb-6", children: "Browse GitHub Plugins" }), _jsx("input", { type: "text", placeholder: "Search plugins...", className: "w-full px-4 py-3 bg-gray-800 text-white border border-gray-700 rounded-lg focus:outline-none focus:border-blue-500 transition" })] }), _jsx("div", { className: "flex-1 overflow-y-auto p-8", children: _jsxs("div", { className: "text-gray-400 text-center py-12", children: [_jsx("p", { className: "text-2xl mb-4", children: "\uD83D\uDD0D Loading plugins from GitHub..." }), _jsx("p", { children: "Check the console for any errors." })] }) })] })), currentPage === 'marketplace' && (_jsxs("div", { className: "flex flex-col h-full bg-gray-900", children: [_jsx("div", { className: "p-8 border-b border-gray-700", children: _jsx("h2", { className: "text-3xl font-bold text-white", children: "\uD83C\uDFA8 PlugHub Marketplace" }) }), _jsx("div", { className: "flex-1 overflow-y-auto p-8", children: _jsx("div", { className: "text-gray-400 text-center py-12", children: _jsx("p", { className: "text-2xl", children: "\uD83D\uDCE4 Upload your plugins here" }) }) })] })), currentPage === 'installed' && (_jsxs("div", { className: "flex flex-col h-full bg-gray-900", children: [_jsx("div", { className: "p-8 border-b border-gray-700", children: _jsx("h2", { className: "text-3xl font-bold text-white", children: "Installed Plugins" }) }), _jsx("div", { className: "flex-1 overflow-y-auto p-8", children: _jsx("div", { className: "text-gray-400 text-center py-12", children: _jsx("p", { className: "text-2xl", children: "No plugins installed yet" }) }) })] })), currentPage === 'settings' && (_jsxs("div", { className: "flex flex-col h-full bg-gray-900", children: [_jsx("div", { className: "p-8 border-b border-gray-700", children: _jsx("h2", { className: "text-3xl font-bold text-white", children: "Settings" }) }), _jsx("div", { className: "flex-1 overflow-y-auto p-8", children: _jsxs("div", { className: "max-w-2xl", children: [_jsx("h3", { className: "text-2xl font-bold text-white mb-6", children: "DAW Configuration" }), _jsx("div", { className: "bg-yellow-900 border border-yellow-700 text-yellow-200 p-4 rounded-lg", children: "No DAWs detected. Please install a DAW to continue." })] }) })] }))] })] }));
}
